# fly.toml app configuration file generated for nosebook-api on 2023-05-24T23:39:33+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nosebook-api"
primary_region = "sin"

[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
